import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/ui/Navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { PostFormProvider } from "@/app/hooks/usePostForm"

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`antialiased `}>

        <PostFormProvider>
          <Navbar />
          
          {children}
        </PostFormProvider>

      </body>
    </html>
  );
}
